### ISSUE TITLE
(V2) (BUG) Error on connect wallet connect

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#461]

**Comment by BitHighlander** [comment]
Unhandled Promise Rejection
Error: Missing or invalid topic field
    at SocketTransport.send (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/IPQSPV2O.chunk.js:671173:13)
    at WalletConnect._sendRequest (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/IPQSPV2O.chunk.js:671958:21)
    at async WalletConnect.killSession (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/IPQSPV2O.chunk.js:671815:5)
    at async LegacyWCService.disconnect (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/IPQSPV2O.chunk.js:677313:7)


recreate
Shows first time you attempt to pair a dapp?
then goes away

**Comment by BitHighlander** [comment]
ok steps to recreate. 

Have walletconnect session

close app

open app

disconect from session after startup
