### ISSUE TITLE
(2.0) Wallet Recovery Broken

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-desktop#504]

**Comment by BitHighlander** [comment]
{
    "message": "Response returned an error code",
    "stack": "ResponseError: Response returned an error code\n    at InfoApi.request (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/62TFS4P5.chunk.js:628549:15)\n    at InfoApi.getFeaturesRaw (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/62TFS4P5.chunk.js:634467:26)\n    at InfoApi.getFeatures (file:///Users/highlander/WebstormProjects/keepkey-desktop/packages/keepkey-desktop/dist/mac-arm64/KeepKey%20Desktop.app/Contents/Resources/app.asar/build/app/static/js/62TFS4P5.chunk.js:634476:26)",
    "kind": "ResponseError"
}


Unable to recover Seed into KeepKey Desktop

Freezes after label select
