### ISSUE TITLE
Keepkey-desktop not able to update firmware. 

### ISSUE THREAD

**Issue by develroo** [keepkey/keepkey-desktop#664]
This is weird because perms seem ok. Though I am guessing as this is the first time I have tried to update it (don't ask) I will probably have to upload a firmware by hand. I notice if I hold the button when I plug it in, it  puts it into a firmware download mode. That shows firmware v1.0.3 ;)

Thoughts? 

```
ls -la /dev/hid*
crw-rw-rw-+ 1 root plugdev 246, 1 Nov 13 09:35 /dev/hidraw1

```
```
groups
user disk cdrom floppy sudo audio dip video plugdev netdev bluetooth docker

```

```
09:34:59.757 › KKStateController detach
KK STATE { state: 'disconnected' }
09:35:06.013 › KKStateController attach
KK STATE { state: 'plugin' }
09:35:06.016 › KKStateController syncState
latestFirmware {
  firmware: {
    version: 'v7.8.0',
    url: 'v7.8.0/firmware.keepkey.bin',
    hash: '31c1cdd945a7331e01b3cced866cb28add5b49eef87c2bbc08370e5aa7daf9bf'
  },
  bootloader: {
    version: 'v2.1.4',
    url: 'bl_v2.1.4/blupdater.bin',
    hash: '6bb7cfd28262fcd61c450fdc3f6932650bdf16a134ab6c1bc6f90b0d1578e620'
  },
  updater: { version: 'v2.1.4' }
}
bootloaderHashes {
  '6397c446f6b9002a8b150bf4b9b4e0bb66800ed099b881ca49700139b0559f10': 'v1.0.0',
  f13ce228c0bb2bdbc56bdcb5f4569367f8e3011074ccc63331348deb498f2d8f: 'v1.0.0',
  d544b5e06b0c355d68b868ac7580e9bab2d224a1e2440881cc1bca2b816752d5: 'v1.0.1',
  ec618836f86423dbd3114c37d6e3e4ffdfb87d9e4c6199cf3e163a67b27498a2: 'v1.0.1',
  cd702b91028a2cfa55af43d3407ba0f6f752a4a2be0583a172983b303ab1032e: 'v1.0.2',
  bcafb38cd0fbd6e2bdbea89fb90235559fdda360765b74e4a8758b4eff2d4921: 'v1.0.2',
  cb222548a39ff6cbe2ae2f02c8d431c9ae0df850f814444911f521b95ab02f4c: 'v1.0.3',
  '917d1952260c9b89f3a96bea07eea4074afdcc0e8cdd5d064e36868bdd68ba7d': 'v1.0.3',
  '6465bc505586700a8111c4bf7db6f40af73e720f9e488d20db56135e5a690c4f': 'v1.0.3',
  db4bc389335e876e942ae3b12558cecd202b745903e79b34dd2c32532708860e: 'v1.0.3',
  '2e38950143cf350345a6ddada4c0c4f21eb2ed337309f39c5dbc70b6c091ae00': 'v1.0.3',
  '83d14cb6c7c48af2a83bc326353ee6b9abdd74cfe47ba567de1cb564da65e8e9': 'v1.0.3',
  '770b30aaa0be884ee8621859f5d055437f894a5c9c7ca22635e7024e059857b7': 'v1.0.4',
  fc4e5c4dc2e5127b6814a3f69424c936f1dc241d1daf2c5a2d8f0728eb69d20d: 'v1.0.4',
  e45f587fb07533d832548402d0e71d8e8234881da54d86c4b699c28a6482b0ee: 'v1.1.0',
  '9bf1580d1b21250f922b68794cdadd6c8e166ae5b15ce160a42f8c44a2f05936': 'v2.0.0',
  e1ad2667d1924e4ddbeb623bd6939e94114d8471b84f8fb056e0c9abf0c4e4f4: 'v2.1.0',
  a3f8c745ff33cd92a7e95d37c76c65523d258a70352ea44a232038ec4ec38dea: 'v2.1.1',
  '3b97596ed612aa29a74a7f51f33ea85fd6e0cfe7340dfbb96f0c17077b363498': 'v2.1.2',
  e6685ab14844d0a381d658d77e13d6145fe7ae80469e5a5360210ae9c3447a77: 'v2.1.3',
  fe98454e7ebd4aef4a6db5bd4c60f52cf3f58b974283a7c1e1fcc5fea02cf3eb: 'v2.1.4'
}
unable to pair webUsb device FirmwareUpdateRequired: Firmware 6.1.0 or later is required to use your KeepKey with this client. Please update your device.
    at new TransportDelegate (/tmp/.mount_KeepKexDtSe0/.yarn/__virtual__/@shapeshiftoss-hdwallet-keepkey-nodewebusb-virtual-ee6a0ebef1/0/cache/@shapeshiftoss-hdwallet-keepkey-nodewebusb-npm-1.52.11-6730b2b406-7bafd865d5.zip/node_modules/@shapeshiftoss/hdwallet-keepkey-nodewebusb/src/transport.ts:14:58)
    at Object.<anonymous> (/tmp/.mount_KeepKexDtSe0/.yarn/__virtual__/@shapeshiftoss-hdwallet-keepkey-nodewebusb-virtual-ee6a0ebef1/0/cache/@shapeshiftoss-hdwallet-keepkey-nodewebusb-npm-1.52.11-6730b2b406-7bafd865d5.zip/node_modules/@shapeshiftoss/hdwallet-keepkey-nodewebusb/src/adapter.ts:23:12)
    at Generator.next (<anonymous>)
    at /tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421754:71
    at new Promise (<anonymous>)
    at __awaiter2 (/tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421736:14)
    at Object.getTransportDelegate (/tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421784:16)
    at Adapter.<anonymous> (/tmp/.mount_KeepKexDtSe0/.yarn/cache/@shapeshiftoss-hdwallet-keepkey-npm-1.52.11-4bf2d79bed-69c345a797.zip/node_modules/@shapeshiftoss/hdwallet-keepkey/src/adapter.ts:145:32)
    at Generator.next (<anonymous>)
    at /tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:420997:71 {
  type: 'FirmwareUpdateRequired'
}
09:35:06.255 › KKStateController HARDWARE_ERROR :( TypeError: cannot open device with path /dev/hidraw1
    at new HID (/tmp/.mount_KeepKexDtSe0/.yarn/unplugged/node-hid-patch-7bd25cf988/node_modules/node-hid/nodehid.js:50:17)
    at new TransportDelegate (/tmp/.mount_KeepKexDtSe0/.yarn/__virtual__/@shapeshiftoss-hdwallet-keepkey-nodehid-virtual-5db2a7bc1a/0/cache/@shapeshiftoss-hdwallet-keepkey-nodehid-npm-1.52.11-457836f4a8-ddaa03d3f0.zip/node_modules/@shapeshiftoss/hdwallet-keepkey-nodehid/src/transport.ts:12:29)
    at Object.<anonymous> (/tmp/.mount_KeepKexDtSe0/.yarn/__virtual__/@shapeshiftoss-hdwallet-keepkey-nodehid-virtual-5db2a7bc1a/0/cache/@shapeshiftoss-hdwallet-keepkey-nodehid-npm-1.52.11-457836f4a8-ddaa03d3f0.zip/node_modules/@shapeshiftoss/hdwallet-keepkey-nodehid/src/adapter.ts:31:12)
    at Generator.next (<anonymous>)
    at /tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421452:71
    at new Promise (<anonymous>)
    at __awaiter2 (/tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421434:14)
    at Object.getTransportDelegate (/tmp/.mount_KeepKexDtSe0/resources/app.asar/build/main.js:421488:16)
    at Adapter.<anonymous> (/tmp/.mount_KeepKexDtSe0/.yarn/cache/@shapeshiftoss-hdwallet-keepkey-npm-1.52.11-4bf2d79bed-69c345a797.zip/node_modules/@shapeshiftoss/hdwallet-keepkey/src/adapter.ts:145:32)
    at Generator.next (<anonymous>)
KK STATE {
  state: 'hardwareError',
  error: 'TypeError: cannot open device with path /dev/hidraw1'
}

```

**Comment by develroo** [comment]
Never mind, Keepkey Updater works so I am on the latest firmware/bootloader. Should have used that earlier. My bad.
